urls.py
from django.urls import path
from . import views

app_name = 'cm_portal'

urlpatterns = [
    path('', views.index, {'template_name': 'cm_portal/index.html', 'title': 'Home'}, name='index'),
    path('about/', views.index, {'template_name': 'cm_portal/about.html', 'title': 'About'}, name='about'),
    path('contact/', views.index, {'template_name': 'cm_portal/contact.html', 'title': 'We look forward to hearing from you!'}, name='contact'),
]

models.py
from django.db import models

# Create your models here.

views.py
from django.shortcuts import render 

# Create your views here.
def index(request, template_name, title):
    return render(request, template_name, {'title': title})

templates/cm_portal/about.html
{% extends 'cm_portal/base.html' %}
{% load static %}

{% block title %}CMPortal V2 | {{ title }}{% endblock %}

{% block header %}
  {% include 'cm_portal/includes/header.html' %}
{% endblock %}

{% block content %}
  <div class="d-flex justify-content-center align-items-center" style="height: 100vh">
    <div class="text-center p-2">
      <p>CMPortal V2 is a web app developed by Camillus MedHaven Nursing Home</p>
      <p>especially designed to provide a digital solution for data such as</p>
      <p>resident admissions, medications and plan of care for easy tracking and</p>
      <p>portability of information.</p> 
      <p>It also plans to provide other services such as a central supplies database</p>
      <p>for easy tracking of inventory and a human resource information system</p>
      <p>as an online solution for data entry, data tracking,</p>
      <p>and data information needs of the Human Resources,</p>
      <p>payroll, management, and accounting functions within a business.</p>  
    </div>
  </div> 
{% endblock %}

templates/cm_portal/base.html
{% extends 'core/base.html' %}

templates/cm_portal/contact.html
{% extends 'cm_portal/base.html' %}
{% load static %}

{% block title %}CMPortal V2 | {{ title }}{% endblock %}

{% block header %}
  {% include 'cm_portal/includes/header.html' %}
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 100vh">
    <div class="text-center p-2">
        

<form>
  <!-- Name input -->
  <div class="form-outline mb-4">
    <input type="text" id="form4Example1" class="form-control" />
    <label class="form-label" for="form4Example1">Name</label>
  </div>

  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="email" id="form4Example2" class="form-control" />
    <label class="form-label" for="form4Example2">Email address</label>
  </div>

  <!-- Message input -->
  <div class="form-outline mb-4">
    <textarea class="form-control" id="form4Example3" rows="4"></textarea>
    <label class="form-label" for="form4Example3">Message</label>
  </div>

  <!-- Checkbox -->
  <div class="form-check d-flex justify-content-center mb-4">
    <input
      class="form-check-input me-2"
      type="checkbox"
      value=""
      id="form4Example4"
      checked
    />
    <label class="form-check-label" for="form4Example4">
      Send me a copy of this message
    </label>
  </div>

  <!-- Submit button -->
  <button type="submit" class="btn btn-primary btn-block mb-4">Send</button>
</form>

    </div>
  </div>
{% endblock %}

templates/cm_portal/includes/footer.html
<section class="">
  <!-- Footer -->
  <footer class="text-center text-white" style="background-color: lightgreen;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        {% if not user.is_authenticated %}
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Register for free</span>
          <a href="{% url 'register' %}" type="button" class="btn btn-outline-light btn-rounded">
            Sign up!
          </a>
        </p>
        {% else %}
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">This website is powered by Python!</span>
        </p>
        {% endif %}
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2018-2021 Copyright:
      <a class="text-white" href="https://web.facebook.com/nursinghomecamillusmedhaven" target="_blank">Camillus MedHaven Nursing Home. </a>All rights reserved. 
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</section>

templates/cm_portal/includes/header.html
<!-- Navbar -->
    {% include 'core/includes/navbar.html' %}
  <!-- Navbar -->
  <div class="card card-intro sky-gradient">
    <div class="card-body white-text rgba-black-light text-center">
      <!--Grid row-->
      <div class="row d-flex justify-content-center">
        <!--Grid column-->
        <div class="col-md-6">
          <h1 class="font-weight-bold h2">{{ title }}</h1>
        </div>
      <!--Grid column-->
      </div>
    <!--Grid row-->
    </div>
  </div>

templates/cm_portal/includes/header1.html
{% load static %}
<!-- Navbar -->
    {% include 'core/includes/navbar.html' %}
  <!-- Navbar -->

  <!-- Background image -->
  <div
    class="p-5 text-center bg-image"
    style="
      background-image: url({% static "img/banner.jpg" %});
      height: 400px;
    "
  >
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.6)">
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          <h1 class="mb-3">St. Camillus MedHaven Nursing Home</h1>
          <h4 class="mb-3">"Your Home with a Heart"</h4>
          {% if not request.user.is_authenticated %}
          <a class="btn btn-outline-light btn-lg" href="{% url 'login' %}" role="button"
            >Sign In</a
          >
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->
  <div class="card card-intro sky-gradient">
    <div class="card-body white-text rgba-black-light text-center">
      <!--Grid row-->
      <div class="row d-flex justify-content-center">
        <!--Grid column-->
        <div class="col-md-6">
          <h1 class="font-weight-bold h2">{{ title }}</h1>
        </div>
      <!--Grid column-->
      </div>
    <!--Grid row-->
    </div>
  </div>

templates/cm_portal/includes/our_services.html
<h3>Our Services</h3>  
<ul class="nav nav-pills flex-column">
  <li class="nav-item">
    <a class="nav-link{% if title == 'Home' %} active{% endif %}" href="{% url 'cm_portal:index' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if title == 'Admissions' or title == 'Admission Detail' %} active{% endif %}" href="{% url 'geriatrics:admissions' %}">Geriatrics</a>
  </li>    
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Health Declaration and Swab Test Results</a>
  </li>    
  </ul>
<hr>

templates/cm_portal/index.html
{% extends 'cm_portal/base.html' %}
{% load static %}

{% block title %}CMPortal V2 | {{ title }}{% endblock %}

{% block header %}
  {% include 'cm_portal/includes/header1.html' %}
{% endblock %}

{% block content %}  
<div class="col-lg-12">
  <div class="accordion accordion-flush" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
      <button
        class="accordion-button collapsed"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#flush-collapseOne"
        aria-expanded="false"
        aria-controls="flush-collapseOne"
      >
        Camillus MedHaven Nursing Home
      </button>
    </h2>
    <div
      id="flush-collapseOne"
      class="accordion-collapse collapse"
      aria-labelledby="flush-headingOne"
      data-mdb-parent="#accordionFlushExample"
    >
      <div class="accordion-body">
        Camillus MedHaven Nursing Home is a Philippine-based nursing home that
        provides resident-oriented, long-term full-time care; rehabilitative therapies;
        and adult daycare services to seniors who need post-hospital or post-operative
        medical attention, whose families are not equipped to give the
        attention they require. Conveniently located in Marikina City, Camillus
        MedHaven is one of the elderly care nursing homes near Cainta, Antipolo,
        Taytay, Angono, and Montalban.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingTwo">
      <button
        class="accordion-button collapsed"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#flush-collapseTwo"
        aria-expanded="false"
        aria-controls="flush-collapseTwo"
      >
        Our Mission
      </button>
    </h2>
    <div
      id="flush-collapseTwo"
      class="accordion-collapse collapse"
      aria-labelledby="flush-headingTwo"
      data-mdb-parent="#accordionFlushExample"
    >
      <div class="accordion-body">
        <p>We commit ourselves to care for our stakeholders with Heart in our Hands by:</p>
      <p>Accompanying and serving with compassion and competence</p>
      <p>Respecting human dignity and individuality</p>
      <p>And upholding excellence in all services</p>

      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingThree">
      <button
        class="accordion-button collapsed"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#flush-collapseThree"
        aria-expanded="false"
        aria-controls="flush-collapseThree"
      >
        Our Vision
      </button>
    </h2>
    <div
      id="flush-collapseThree"
      class="accordion-collapse collapse"
      aria-labelledby="flush-headingThree"
      data-mdb-parent="#accordionFlushExample"
    >
      <div class="accordion-body">
        <p>Camillus Medhaven,</p>
      <p>a Camillian Healthcare institution,</p>
      <p>envisions to provide</p>
      <p>a home,</p>
      <p>a nurturing community</p>
      <p>and</p>
      <p>a center of excellence</p>
      <p>for holistic care</p>
      <p>of the elderly</p>
      <p>and persons in need</p>
      <p>of convalescent</p>
      <p>and palliative care.</p>

      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingFour">
      <button
        class="accordion-button collapsed"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#flush-collapseFour"
        aria-expanded="false"
        aria-controls="flush-collapseFour"
      >
        Our Services
      </button>
    </h2>
    <div
      id="flush-collapseFour"
      class="accordion-collapse collapse"
      aria-labelledby="flush-headingFour"
      data-mdb-parent="#accordionFlushExample"
    >
      <div class="accordion-body">
        <div class="list-group">
        <a href="{% url 'geriatrics:admissions' %}" class="list-group-item list-group-item-action">
          <i class="fas fa-hand-holding-heart"></i> Geriatrics
        </a>
        <a href="#" class="list-group-item list-group-item-action">
          <i class="fas fa-temperature-high"></i> Health Declaration and Swab Test Results
        </a>
	<a href="{% url 'admin:index' %}" class="list-group-item list-group-item-action">
          <i class="fas fa-user-friends"></i> St. Camillus MedHaven Admin
        </a>
      </div>
      </div>
    </div>
  </div>

</div>      
</div> 
 
{% endblock %}